/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7ff3bb0f1092404b73cee7d7a766c7dc)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env {
	}
}
interface Env extends Cloudflare.Env {}
