/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 0aa2a75570b7b7e86df260126e8e5805)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		AI_MODEL: "@cf/qwen/qwen3-30b-a3b-fp8";
		DEEPSEEK_API_KEY: string;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_MODEL" | "DEEPSEEK_API_KEY">> {}
}
